name: Release (Manual) 3

on: 
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Build with Maven
        run: mvn -B package --file pom.xml

#      - name: Publish to GitHub Packages Apache Maven
#        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
#        env:
#          GITHUB_TOKEN: ${{ github.token }}

      - name: Configure git
          run: |
            git config --global committer.email "noreply@github.com"
            git config --global committer.name "GitHub"
            git config --global author.email "${GITHUB_ACTOR}@users.noreply.github.com"
            git config --global author.name "${GITHUB_ACTOR}":
            git config --global hub.protocol https

      - name: Prepare and perform release
          run: mvn -B release:prepare release:perform -Dusername=GITHUB_ACTOR -Dpassword=GITHUB_TOKEN
        env:
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
